routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/admin/login', 'Admin\AuthController@index')->name('login');
Route::post('/admin/login', 'Admin\AuthController@login');
Route::post('/admin/logout', 'Admin\AuthController@logout')->name('logout');

Route::group(['prefix' => 'admin', 'middleware' => 'auth'], function () {
    Route::get('/dashboard', 'Admin\DashboardController@index')->name('admin.dashboard');
    Route::resource('/tags', 'Admin\TagController');
    Route::resource('/categories', 'Admin\CategoryController');
    Route::resource('/articles', 'Admin\ArticleController');
    Route::resource('/articles/edit', 'Admin\ArticleController@edit');
    Route::resource('/events', 'Admin\EventController');
    Route::resource('/pkm', 'Admin\PkmController');
    Route::resource('/asisten-lecturer', 'Admin\AsistenController');
    Route::resource('/startups', 'Admin\StartupController');
});

resources/views/layouts/admin/edit.blade.php
@extends('layouts.admin.main')

@section('title', 'Edit Article SLIBC')

@section('content')
<div class="col-xl-8 order-xl-1 mx-auto">
    <div class="card">
        <div class="card-header">
            <div class="row align-items-center">
                <div class="col-8">
                    <h3 class="mb-0">Edit Article</h3>
                </div>
            </div>
        </div>
        <div class="card-body">
            <form>
                <!-- Address -->
                <div class="pl-lg-4">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group">
                                <input type="file" class="custom-file-input" id="customFileLang" lang="en">
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group">
                                <label class="form-control-label" for="title">Judul</label>
                                <input id="title" class="form-control" type="text">
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group">
                                <label class="form-control-label" for="category">Kategory</label>
                                <select name="#" id="category" class="form-control">
                                    <option value="#">Teknologi</option>
                                    <option value="#">Inovasi</option>
                                    <option value="#">Trend</option>
                                    <option value="#">Prestasi</option>
                                    <option value="#">Startup Kampus</option>
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group">
                                <label class="form-control-label" for="tags">Tags</label>
                                <input id="tags" class="form-control" type="text">
                            </div>
                        </div>
                    </div>
                </div>
                <div class="pl-lg-4">
                    <div class="form-group">
                        <label class="form-control-label">Content</label>
                        <textarea rows="4" class="form-control" placeholder="A few words about you ..."></textarea>
                    </div>
                </div>
                <div class="pl-lg-4">
                    <div class="form-group">
                        <button type="button" class="btn btn-default btn-block">Submit form</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/admin/main.blade.php
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Start your development with a Dashboard for Bootstrap 4.">
    <meta name="author" content="Creative Tim">
    <title>@yield('title')</title>
    <!-- Favicon -->
    <link rel="icon" href="/admin/assets/img/brand/favicon.png" type="image/png">
    <!-- Fonts -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700">
    <!-- Icons -->
    <link rel="stylesheet" href="/admin/assets/vendor/nucleo/css/nucleo.css" type="text/css">
    <link rel="stylesheet" href="/admin/assets/vendor/@fortawesome/fontawesome-free/css/all.min.css" type="text/css">
    <!-- Page plugins -->
    <!-- Argon CSS -->
    <link rel="stylesheet" href="/admin/assets/css/argon.css?v=1.2.0" type="text/css">
    <style>
        .display-0 {
            display: none
        }

    </style>
</head>
<body>
    <!-- Sidenav -->
    @include('layouts.admin.sidebar')

    <!-- Main content -->
    <div class="main-content" id="panel">
        <!-- Topnav -->
        <nav class="navbar navbar-top navbar-expand navbar-dark bg-primary border-bottom">
            <div class="container-fluid">
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Search form -->
                    <form class="navbar-search navbar-search-light form-inline mr-sm-3" id="navbar-search-main">
                        <div class="form-group mb-0">
                            <div class="input-group input-group-alternative input-group-merge">
                                <div class="input-group-prepend">
                                    <span class="input-group-text"><i class="fas fa-search"></i></span>
                                </div>
                                <input class="form-control" placeholder="Search" type="text">
                            </div>
                        </div>
                        <button type="button" class="close" data-action="search-close" data-target="#navbar-search-main" aria-label="Close">
                            <span aria-hidden="true">×</span>
                        </button>
                    </form>
                    <!-- Navbar links -->

                    <ul class="navbar-nav align-items-center  ml-md-auto ml-md-0 ">
                        <li class="nav-item d-xl-none">
                            <!-- Sidenav toggler -->
                            <div class="pr-3 sidenav-toggler sidenav-toggler-dark" data-action="sidenav-pin" data-target="#sidenav-main">
                                <div class="sidenav-toggler-inner">
                                    <i class="sidenav-toggler-line"></i>
                                    <i class="sidenav-toggler-line"></i>
                                    <i class="sidenav-toggler-line"></i>
                                </div>
                            </div>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link pr-0" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <div class="media align-items-center">
                                    <span class="avatar avatar-sm rounded-circle">
                                        <img alt="Image placeholder" src="/admin/assets/img/theme/team-4.jpg">
                                    </span>
                                    <div class="media-body  ml-2  d-none d-lg-block">
                                        <span class="mb-0 text-sm  font-weight-bold">{{ auth()->user()->name }}</span>
                                    </div>
                                </div>
                            </a>
                            <div class="dropdown-menu  dropdown-menu-right ">
                                <a href="#!" class="dropdown-item">
                                    <i class="ni ni-single-02"></i>
                                    <span>Profile</span>
                                </a>
                                <a href="{{ route('logout') }}" class="dropdown-item" onclick="event.preventDefault(); document.getElementById('logout').submit()">
                                    <i class="ni ni-user-run"></i>
                                    <span>Logout</span>
                                </a>

                                <form action="{{ route('logout') }}" method="post" id="logout">
                                    @csrf
                                </form>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Header -->
        <div class="header pb-6">
            <div class="container-fluid py-3">
                <div class="header-body">
                    <!-- Card stats -->
                    <div class="row">
                        @yield('content')
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script src="/admin/assets/vendor/jquery/dist/jquery.min.js"></script>
    <script src="/admin/assets/vendor/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="/admin/assets/vendor/js-cookie/js.cookie.js"></script>
    <script src="/admin/assets/vendor/jquery.scrollbar/jquery.scrollbar.min.js"></script>
    <script src="/admin/assets/vendor/jquery-scroll-lock/dist/jquery-scrollLock.min.js"></script>
    <!-- Optional JS -->
    <script src="/admin/assets/vendor/chart.js/dist/Chart.min.js"></script>
    <script src="/admin/assets/vendor/chart.js/dist/Chart.extension.js"></script>
    <!-- Argon JS -->
    <script src="/admin/assets/js/argon.js?v=1.2.0"></script>
    {{-- ajax cdn --}}
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
</body>
</html>

resources/views/layouts/admin/sidebar.blade.php
<nav class="sidenav navbar navbar-vertical  fixed-left  navbar-expand-xs navbar-light bg-white" id="sidenav-main">
    <div class="scrollbar-inner">
        <!-- Brand -->
        <div class="sidenav-header  align-items-center">
            <a class="navbar-brand" href="{{ route('admin.dashboard') }}">
                <img src="/assets/img/slibc.png" class="navbar-brand-img" alt="SLIBC">
            </a>
        </div>
        <div class="navbar-inner">
            <!-- Collapse -->
            <div class="collapse navbar-collapse" id="sidenav-collapse-main">
                <!-- Nav items -->
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link{{ request()->is('admin/dashboard') ? ' active' : '' }}" href="/admin/dashboard">
                            <i class="ni ni-tv-2 text-primary"></i>
                            <span class="nav-link-text">Dashboard</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link{{ request()->is('admin/tags') ? ' active' : '' }}" href="{{ route('tags.index') }}">
                            <i class="ni ni-tag text-blue"></i>
                            <span class="nav-link-text">Tags</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link{{ request()->is('admin/categories') ? ' active' : '' }}" href="{{ route('categories.index') }}">
                            <i class="ni ni-book-bookmark text-blue"></i>
                            <span class="nav-link-text">Kategori</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link{{ request()->is('admin/articles') ? ' active' : '' }}" href="{{ route('articles.index') }}">
                            <i class="ni ni-book-bookmark text-blue"></i>
                            <span class="nav-link-text">Articles</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link{{ request()->is('admin/events') ? ' active' : '' }}" href="{{ route('events.index') }}">
                            <i class="ni ni-square-pin text-blue"></i>
                            <span class="nav-link-text">Event</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link{{ request()->is('admin/pkm') ? ' active' : '' }}" href="{{ route('pkm.index') }}">
                            <i class="ni ni-bulb-61 text-blue"></i>
                            <span class="nav-link-text">PKM</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link{{ request()->is('admin/asisten-lecturer') ? ' active' : '' }}" href="{{ route('asisten-lecturer.index') }}">
                            <i class="ni ni-circle-08 text-blue"></i>
                            <span class="nav-link-text">Asisten Lecturer</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link{{ request()->is('admin/startups') ? ' active' : '' }}" href="{{ route('startups.index') }}">
                            <i class="ni ni-air-baloon text-blue"></i>
                            <span class="nav-link-text">List Startup</span>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</nav>